apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-saver
  labels:
    app: event-saver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-saver
  template:
    metadata:
      labels:
        app: event-saver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "event-saver"
        dapr.io/port: "8080"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: event-saver
        image: mchmarny/event-saver:v0.1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: SOURCE_TOPIC_NAME
          value: "events"
        - name: TARGET_STORE_NAME
          value: "store"
