apiVersion: v1
kind: Service
metadata:
  name: event-saver
  labels:
    app: event-saver
spec:
  ports:
  - port: 3500
    protocol: TCP
    targetPort: 3500
  selector:
    app: event-saver
  type: LoadBalancer
